export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS' ;
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
